--- #YAML:1.0
name: POE
version: 0.3202
author:
  - Rocco Caputo <rcaputo@cpan.org>
abstract: A portable networking and multitasking framework.
license: perl
generated_by: Module::Build version 0.261, without YAML.pm
