--- #YAML:1.0
name: POE
version: 0.30
author:
  - Rocco Caputo <rcaputo@cpan.org>
abstract: portable multitasking and networking framework for Perl
license: perl
generated_by: Module::Build version 0.2604, without YAML.pm
