---
name: POE
version: 0.9917
author:
  - 'Rocco Caputo <rcaputo@cpan.org>'
abstract: A portable networking and multitasking framework.
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 0
  Errno: 1.09
  Exporter: 0
  File::Spec: 0.87
  IO: 1.2
  POSIX: 1.02
  Socket: 1.7
  Test::Harness: 2.26
recommends:
  Time::HiRes: 1.59
provides:
  POE:
    file: lib/POE.pm
    version: 0.9917
  POE::API::Ctl:
    file: lib/POE/API/Ctl.pm
    version: 1.1903
  POE::API::ResLoader:
    file: lib/POE/API/ResLoader.pm
    version: 1.1903
  POE::Component:
    file: lib/POE/Component.pm
    version: 1.2116
  POE::Component::Client::TCP:
    file: lib/POE/Component/Client/TCP.pm
    version: 1.2162
  POE::Component::Server::TCP:
    file: lib/POE/Component/Server/TCP.pm
    version: 1.2106
  POE::Driver:
    file: lib/POE/Driver.pm
    version: 1.1903
  POE::Driver::SysRW:
    file: lib/POE/Driver/SysRW.pm
    version: 1.2144
  POE::Filter:
    file: lib/POE/Filter.pm
    version: 1.2145
  POE::Filter::Block:
    file: lib/POE/Filter/Block.pm
    version: 1.1920
  POE::Filter::Grep:
    file: lib/POE/Filter/Grep.pm
    version: 1.2106
  POE::Filter::HTTPD:
    file: lib/POE/Filter/HTTPD.pm
    version: 1.2155
  POE::Filter::Line:
    file: lib/POE/Filter/Line.pm
    version: 1.1920
  POE::Filter::Map:
    file: lib/POE/Filter/Map.pm
    version: 1.2106
  POE::Filter::RecordBlock:
    file: lib/POE/Filter/RecordBlock.pm
    version: 1.2106
  POE::Filter::Reference:
    file: lib/POE/Filter/Reference.pm
    version: 1.2025
  POE::Filter::Stackable:
    file: lib/POE/Filter/Stackable.pm
    version: 1.2145
  POE::Filter::Stream:
    file: lib/POE/Filter/Stream.pm
    version: 1.1920
  POE::Kernel:
    file: lib/POE/Kernel.pm
    version: 1.2157
  POE::Loop:
    file: lib/POE/Loop.pm
    version: 1.2116
  POE::Loop::Event:
    file: lib/POE/Loop/Event.pm
    version: 1.2126
  POE::Loop::Gtk:
    file: lib/POE/Loop/Gtk.pm
    version: 1.2004
  POE::Loop::IO_Poll:
    file: lib/POE/Loop/IO_Poll.pm
    version: 1.2149
  POE::Loop::PerlSignals:
    file: lib/POE/Loop/PerlSignals.pm
    version: 1.1980
  POE::Loop::Select:
    file: lib/POE/Loop/Select.pm
    version: 1.1980
  POE::Loop::Tk:
    file: lib/POE/Loop/Tk.pm
    version: 1.1980
  POE::Loop::TkActiveState:
    file: lib/POE/Loop/TkActiveState.pm
    version: 1.1980
  POE::Loop::TkCommon:
    file: lib/POE/Loop/TkCommon.pm
    version: 1.2163
  POE::NFA:
    file: lib/POE/NFA.pm
    version: 1.2135
  POE::Pipe:
    file: lib/POE/Pipe.pm
    version: 1.2116
  POE::Pipe::OneWay:
    file: lib/POE/Pipe/OneWay.pm
    version: 1.2116
  POE::Pipe::TwoWay:
    file: lib/POE/Pipe/TwoWay.pm
    version: 1.2116
  POE::Queue:
    file: lib/POE/Queue.pm
    version: 1.1903
  POE::Queue::Array:
    file: lib/POE/Queue/Array.pm
    version: 1.1979
  POE::Resource:
    file: lib/POE/Resource.pm
    version: 1.2116
  POE::Resource::Aliases:
    file: lib/POE/Resource/Aliases.pm
    version: 1.2087
  POE::Resource::Controls:
    file: lib/POE/Resource/Controls.pm
    version: 1.2087
  POE::Resource::Events:
    file: lib/POE/Resource/Events.pm
    version: 1.2087
  POE::Resource::Extrefs:
    file: lib/POE/Resource/Extrefs.pm
    version: 1.2087
  POE::Resource::FileHandles:
    file: lib/POE/Resource/FileHandles.pm
    version: 1.2087
  POE::Resource::SIDs:
    file: lib/POE/Resource/SIDs.pm
    version: 1.2087
  POE::Resource::Sessions:
    file: lib/POE/Resource/Sessions.pm
    version: 1.2126
  POE::Resource::Signals:
    file: lib/POE/Resource/Signals.pm
    version: 1.2157
  POE::Resource::Statistics:
    file: lib/POE/Resource/Statistics.pm
    version: 1.2087
  POE::Resources:
    file: lib/POE/Resources.pm
    version: 1.2106
  POE::Session:
    file: lib/POE/Session.pm
    version: 1.2159
  POE::Wheel:
    file: lib/POE/Wheel.pm
    version: 1.1903
  POE::Wheel::Curses:
    file: lib/POE/Wheel/Curses.pm
    version: 1.2102
  POE::Wheel::FollowTail:
    file: lib/POE/Wheel/FollowTail.pm
    version: 1.2160
  POE::Wheel::ListenAccept:
    file: lib/POE/Wheel/ListenAccept.pm
    version: 1.2106
  POE::Wheel::ReadLine:
    file: lib/POE/Wheel/ReadLine.pm
    version: 1.2137
  POE::Wheel::ReadLine::Keymap:
    file: lib/POE/Wheel/ReadLine.pm
  POE::Wheel::ReadWrite:
    file: lib/POE/Wheel/ReadWrite.pm
    version: 1.2106
  POE::Wheel::Run:
    file: lib/POE/Wheel/Run.pm
    version: 1.2106
  POE::Wheel::SocketFactory:
    file: lib/POE/Wheel/SocketFactory.pm
    version: 1.2106
no_index:
  directory:
    - mylib
    - t
generated_by: Module::Build version 0.2805
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
